
server:
  port: 8088
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: okx-trading
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/okx_trading?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: resources/schema.sql
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
  # SpringFox兼容配置 - 解决与Spring Boot 2.7.x的兼容性问题
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # 编码配置
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  # 允许Bean定义覆盖
  main:
    allow-bean-definition-overriding: true

# OKX API配置
okx:
  api:
    base-url: https://www.okx.com
    api-key: ${OKX_API_KEY:}
    secret-key: ${OKX_SECRET_KEY:}
    passphrase: ${OKX_PASSPHRASE:}
    use-mock-data: false # 是否使用模拟数据，true:使用模拟数据，false:调用真实API
    timeout: 30 # 请求超时时间(秒)
    connection-mode: REST # 连接模式: REST或WEBSOCKET，默认WEBSOCKET
    ws:
      public-channel: wss://ws.okx.com:8443/ws/v5/public
      bussiness-channel: wss://ws.okx.com:8443/ws/v5/business
      private-channel: wss://ws.okx.com:8443/ws/v5/private
  proxy:
    enabled: true # 是否启用代理
    host: localhost
    port: 10809
  historical-data:
    batch-size: 100
    max-threads: 10


# 日志配置
logging:
  level:
    root: INFO
    com.okx.trading: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Swagger配置
springfox:
  documentation:
    swagger-ui:
      enabled: true


# Swagger文档配置
springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui
